/** 与 backend/app/core/seed.py DEFAULT_PERMISSIONS 对齐 */
export const PermissionCode = {
  USER_MANAGE: 'user.manage',
  ROLE_MANAGE: 'role.manage',
  PERMISSION_MANAGE: 'permission.manage',
  DEPARTMENT_MANAGE: 'department.manage',
  SETTING_MANAGE: 'setting.manage',
  PRINT_TEMPLATE_MANAGE: 'print_template.manage',
  NOTIFICATION_VIEW: 'notification.view',
  ATTENDANCE_MANAGE: 'attendance.manage',
  SKILL_MANAGE: 'skill.manage',
  DASHBOARD_VIEW: 'dashboard.view',
  ATTACHMENT_VIEW: 'attachment.view',
  OPERATION_LOG_VIEW: 'operation_log.view',
  PRODUCT_MANAGE: 'product.manage',
  SKU_MANAGE: 'sku.manage',
  PROCESS_MANAGE: 'process.manage',
  PRICE_MANAGE: 'price.manage',
  CUSTOMER_MANAGE: 'customer.manage',
  CRM_SALES: 'crm.sales',
  ORDER_MANAGE: 'order.manage',
  PLAN_MANAGE: 'plan.manage',
  WORK_MANAGE: 'work.manage',
  TASK_MANAGE: 'task.manage',
  DISPATCH_MANAGE: 'dispatch.manage',
  REPORT_SUBMIT: 'report.submit',
  REPORT_AUDIT: 'report.audit',
  REPORT_VIEW: 'report.view',
  SALARY_VIEW: 'salary.view',
  SALARY_MANAGE: 'salary.manage',
  TRACE_QUERY: 'trace.query',
  WAREHOUSE_MANAGE: 'warehouse.manage',
  FINANCE_MANAGE: 'finance.manage',
  EQUIPMENT_MANAGE: 'equipment.manage',
  DICT_MANAGE: 'dict.manage',
  MATERIAL_MANAGE: 'material.manage',
  SUPPLIER_MANAGE: 'supplier.manage',
  BOM_MANAGE: 'bom.manage',
  PURCHASE_MANAGE: 'purchase.manage',
  AI_USE: 'ai.use',
  AI_ALERT_VIEW: 'ai.alert.view',
  AI_REPORT_ASSIST: 'ai.report_assist',
} as const

export type PermissionCodeType = (typeof PermissionCode)[keyof typeof PermissionCode]
