DEFAULT_PERMISSIONS: list[tuple[str, str]] = [
    ("user.manage", "用户管理"),
    ("role.manage", "角色管理"),
    ("permission.manage", "权限点管理"),
    ("department.manage", "部门管理"),
    ("setting.manage", "系统设置"),
    ("print_template.manage", "打印模板"),
    ("notification.view", "消息通知"),
    ("attendance.manage", "考勤管理"),
    ("skill.manage", "技能标签"),
    ("dashboard.view", "看板查看"),
    ("attachment.view", "附件查看"),
    ("operation_log.view", "操作日志查看"),
    ("product.manage", "产品管理"),
    ("sku.manage", "产品型号管理"),
    ("process.manage", "工序管理"),
    ("price.manage", "工价管理"),
    ("customer.manage", "客户管理"),
    ("order.manage", "订单管理"),
    ("plan.manage", "生产计划管理"),
    ("work.manage", "工单管理"),
    ("task.manage", "任务管理"),
    ("dispatch.manage", "派工管理"),
    ("report.submit", "报工提交"),
    ("report.audit", "报工审核"),
    ("report.view", "报表查看"),
    ("salary.view", "工资查看"),
    ("salary.manage", "工资管理"),
    ("trace.query", "溯源查询"),
    ("equipment.manage", "设备管理"),
    ("dict.manage", "字典管理"),
    ("material.manage", "物料管理"),
    ("supplier.manage", "供应商管理"),
    ("bom.manage", "BOM管理"),
    ("exec_dashboard.view", "老板看板查看"),
    ("ai.use", "AI功能"),
    ("ai.alert.view", "AI预警"),
    ("purchase.manage", "采购管理"),
    ("finance.manage", "财务管理"),
    ("warehouse.view", "库存查看"),
    ("warehouse.manage", "库存管理"),
    ("production.plan", "生产排产"),
    ("workorder.view", "工单查看"),
    ("workorder.manage", "工单管理"),
    ("crm.sales", "销售CRM"),
    ("crm.admin", "CRM管理"),
    ("order.view", "订单查看"),
    ("order.create", "订单创建"),
    ("order.edit", "订单编辑"),
    ("task.view", "任务查看"),
    ("task.assign", "任务指派"),
    ("report.approve", "报工审批"),
    ("qc.inspect", "质检检验"),
    ("qc.approve", "质检审批"),
    ("customer.view", "客户查看"),
    ("equipment.view", "设备查看"),
]

DEFAULT_ROLES: list[tuple[str, str]] = [
    ("admin", "管理员"),
    ("leader", "班组长"),
    ("qc", "质检员"),
    ("employee", "员工"),
    ("customer", "客户"),
]

ROLE_PERMISSION_PRESETS: dict[str, set[str]] = {
    "admin": {code for code, _ in DEFAULT_PERMISSIONS},
    "qc": {"report.audit", "trace.query", "salary.view"},
    "leader": {"dispatch.manage", "report.audit", "report.submit", "salary.view", "dashboard.view", "report.view",
               "order.manage", "plan.manage", "work.manage", "task.manage", "notification.view", "attendance.manage"},
    "employee": {"report.submit", "salary.view", "notification.view"},
    "customer": {"notification.view"},
}
